### PR TITLE
GetResponse serialization

### PR DESCRIPTION
**Pull request by isidroas**
- Catched error with unit tests
- fixed test

### CODE REVIEW

**Comment by isidroas** [comment]
Hello @Krolken I have seen that this is already fixed in the branch [23.1.0alfa](https://github.com/pwitab/dlms-cosem/compare/master...23.1.0alfa#diff-48f47174dd410102e5d0085069c9a86b92d239b17089532e07dd68c331cb5383L278)

When will that branch be merged to master?

Should I close this merge request?

**Comment by Krolken** [comment]
Implemented in later versions. Closing. Thanks for caring enough to try and fix it 😄

**Comment by isidroas** [comment]
Could you merge it to master? I see that the but is still present, because [23.1.0alfa](https://github.com/pwitab/dlms-cosem/compare/master...23.1.0alfa#diff-48f47174dd410102e5d0085069c9a86b92d239b17089532e07dd68c331cb5383L278) hasn't been merged yet

**Comment by isidroas** [comment]
That branch also has an important fix:
```diff
diff --git a/dlms_cosem/io.py b/dlms_cosem/io.py
--- a/dlms_cosem/io.py
+++ b/dlms_cosem/io.py
@@ -15,6 +15,7 @@ import attr
 import serial
 
 from dlms_cosem import exceptions
+from dlms_cosem.protocol.wrappers import WrapperHeader, WrapperProtocolDataUnit
 
 from typing import *
 

```

**Pull request closed without merging**
